version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WORKERS=1  # Adjusted for better GPU utilization
      - BATCH_SIZE=16  # Increased for 16GB GPU
      - MAX_AUDIO_LENGTH=300
      - MODEL_PATH=facebook/seamless-m4t-v2-large
      - LOAD_MODEL_ON_STARTUP=true
      - TRANSFORMERS_CACHE=/home/appuser/.cache/huggingface
      - HF_HOME=/home/appuser/.cache/huggingface
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    volumes:
      - huggingface_cache:/home/appuser/.cache/huggingface
    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s  # Increased timeout for model loading
      retries: 5
      start_period: 60s  # Give more time for initial model loading

  # Optional Nginx reverse proxy
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  huggingface_cache:
    # Named volume for persistent storage